### ISSUE TITLE
Icon not showing

### ISSUE THREAD

**Issue by ottlinger** [coliff/bootstrap-show-password-toggle#11]
Thanks for your great work - I've downloaded CSS and JS file via
https://raw.githubusercontent.com/coliff/bootstrap-show-password-toggle/master/css/show-password-toggle.css
but the icon is not rendered in the password field and only a gray rectangular is shown in Chrome browser.

Same is happening with min.css as well.

I do use the following bootstrap files:
* https://getbootstrap.com/docs/4.0/examples/signin/signin.css
* https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css

Do I miss something?

Btw: https://coliff.github.io/bootstrap-show-password-toggle/tests/bootstrap4-sign-in/ does not render the icon in Chrome as well.

Thanks

**Comment by coliff** [comment]
heya. I've just re-tested and the icon is showing as expected. I think there must be some issue with your setup. Maybe a browser extension is interfering or something? Please see if any issues in your DevTools console. If issue persists post back a screenshot and mention which Operating system and exact Chrome version you're using. Have you tried in a different browser?

Btw - when testing locally make sure you use the latest Bootstrap 4.6 files - not 4.0 beta!
https://getbootstrap.com/docs/4.6/getting-started/introduction/#starter-template

**Comment by coliff** [comment]
Tested successfully on Chrome for MacOS and Windows 10

![image](https://user-images.githubusercontent.com/1212885/109409462-38552b00-79d6-11eb-8cb9-d7bdbdadeedc.png)

**Comment by ottlinger** [comment]
Thanks for the comment - I wasn't aware of the fact that the eye is only shown when characters are typed into the password field.

The problem was solved by changing the order of CSS-includes. Thanks for your feedback. Works like a charm now under MacOS/Chrome and FF.
