### ISSUE TITLE
Hide toggle on Edge (Chromium) as it has a native ‘show-password’ toggle

### ISSUE THREAD

**Issue by coliff** [coliff/bootstrap-show-password-toggle#2]
Microsoft Edge has a built-in 'show-password' toggle which initiates on the initial input.

We could potentially rely on user-agent detection to hide 'bootstrap-show-password-toggle' on Edge so only the native toggle is visible.

![image](https://user-images.githubusercontent.com/1212885/86735507-d3774a00-c06d-11ea-91f9-28558e9bd3e5.png)

**Comment by FaresAhmedb** [comment]
The password reveal button can be controlled with the `::-ms-reveal` pseudo element.
```html
<style>
    ::-ms-reveal {
        display: none;
    }
</style>
```
![Screenshot-2021-05-27-111957](https://user-images.githubusercontent.com/73843130/119801253-d4130c00-bedd-11eb-9d21-fc07a1b1077f.png)
*Source: https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal#remove-the-password-reveal-control*

**Comment by coliff** [comment]
ah- awesome! I'll add that in a PR now. thanks!
